### ISSUE TITLE
Cannot rebuild with node-gyp

### ISSUE THREAD

**Issue by joshuawarnock** [DoubleSpout/nodeClientSession#7]
I cloned the repo into my node_modules, cd into nodeClientSession and node-gyp rebuild.

OUTPUT BELOW:

~/webstormprojects/mymsttest/node_modules/nodeClientSession $node-gyp rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.0
gyp info using node@5.6.0 | darwin | x64
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jwarnock/webstormprojects/mymsttest/node_modules/nodeClientSession/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/jwarnock/.node-gyp/5.6.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/jwarnock/.node-gyp/5.6.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/jwarnock/webstormprojects/mymsttest/node_modules/nodeClientSession',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/client_session/src/clientsession.o
In file included from ../src/clientsession.cpp:2:
../src/client_session_class.h:13:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> csessionGet(const Arguments& args);
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/jwarnock/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../src/clientsession.cpp:2:
../src/client_session_class.h:14:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
  static Handle<Value> csessionSet(const Arguments& args);
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/jwarnock/.node-gyp/5.6.0/include/node/v8.h:139:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/clientsession.cpp:10:15: error: calling a protected constructor of class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/jwarnock/.node-gyp/5.6.0/include/node/v8.h:889:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../src/clientsession.cpp:14:27: error: cannot initialize a parameter of type 'v8::Isolate _' with an lvalue of type 'Handlev8::Value
      (const v8::internal::Arguments &)'
           FunctionTemplate::New(Csession_Class::csessionGet)->GetFunction());
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jwarnock/.node-gyp/5.6.0/include/node/v8.h:4349:16: note: passing argument to parameter 'isolate' here
      Isolate_ isolate, FunctionCallback callback = 0,
               ^
../src/clientsession.cpp:13:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("csessionGet"),
              ~~~~~~~~^
../src/clientsession.cpp:18:27: error: cannot initialize a parameter of type 'v8::Isolate *' with an lvalue of type 'Handlev8::Value
      (const v8::internal::Arguments &)'
           FunctionTemplate::New(Csession_Class::csessionSet)->GetFunction());
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jwarnock/.node-gyp/5.6.0/include/node/v8.h:4349:16: note: passing argument to parameter 'isolate' here
      Isolate\* isolate, FunctionCallback callback = 0,
               ^
../src/clientsession.cpp:17:23: error: no member named 'NewSymbol' in 'v8::String'
  target->Set(String::NewSymbol("csessionSet"),
              ~~~~~~~~^
7 errors generated.
make: **\* [Release/obj.target/client_session/src/clientsession.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/"user"/webstormprojects/mymsttest/node_modules/nodeClientSession
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok

**Comment by jihyunmin** [comment]
I'm having the same issue. Everything was working fine locally, but I've been having issues trying to deploy my project via AWS Ubuntu Server 14.04 LTS (HVM).

When I run sudo npm install client-session in my ec2 instance, I get the following output:

argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "client-session"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE

npm ERR! client-session@0.1.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the client-session@0.1.7 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the client-session package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs client-session
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls client-session
npm ERR! There is likely additional logging output above.

I've updated node and npm as well as gyp rebuild

gyp: binding.gyp not found (cwd: /var/www/flywheel) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.13.0-74-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure"
gyp ERR! cwd /var/www/flywheel
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 

so when I run
find /. -name "building.gyp", I get permission denied and doing sudo find /. -name "building.gyp" returns nothing.

**Comment by DoubleSpout** [comment]
sorry the module is no longer maintained~
